image: python:latest

stages:
  - staticcheck
  - test
  - deploy

vastaticcheck:
  before_script:
    - pip install flake8 isort
  script:
    - flake8 .
    - isort -c
  stage: staticcheck

test:
  before_script:
    - pip install -Ur requirements.txt
    - python manage.py migrate
    - python manage.py collectstatic --noinput
  script:
    - python manage.py test
  stage: test

deploy to production:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  script:
    - git-push ssh://dokku@vms.stavros.io:16022/spamnesty
  environment: production
  only:
    - master
